version: "3.7"
services:
  db:
    image: postgres:15
    container_name: db_bmc_app
    command: -p 1221
    expose:
      - 1221
    env_file:
      - .env

  redis:
    image: redis:7
    container_name: redis_bmc_app
    command: --port 5370
    expose:
      - 5370

  web_app:
    build:
      context: .
    container_name: web_bmc_app
    command: ["/bmc_app/scripts/app.sh"]
    env_file:
      - .env
    ports:
      - 9999:8000
    depends_on:
      - db
      - redis
    
  celery:
    build:
      context: .
    container_name: celery_bmc_app
    env_file:
      - .env
    command: ["/bmc_app/scripts/celery.sh", "celery"]
    depends_on:
      - redis

  flower:
    build:
      context: .
    container_name: flower_bmc_app
    env_file:
      - .env
    command: ["/bmc_app/scripts/celery.sh", "flower"]
    depends_on:
      - redis
      - celery
    ports:
      - 8888:5555